#!/bin/bash
# ============================================================
# check_orphaned_files.sh
#
# Detect Dart files under lib/ that are never imported by any
# other file in the project.
#
# Usage:
#   chmod +x scripts/check_orphaned_files.sh
#   ./scripts/check_orphaned_files.sh
#
# Exit code:
#   0  – no orphaned files found
#   1  – orphaned files detected
# ============================================================

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LIB_DIR="$PROJECT_ROOT/lib"

echo "🔍 Scanning for orphaned Dart files in lib/ ..."
echo ""

orphaned_count=0
total_count=0

# Files that are never imported by design
SKIP_FILES=(
  "lib/main.dart"               # App entry point
  "lib/firebase_options.dart"   # Auto-generated by FlutterFire CLI
)

while IFS= read -r file; do
    total_count=$((total_count + 1))
    rel_path="${file#$PROJECT_ROOT/}"

    # Normalise path separators (Windows compat)
    rel_path="${rel_path//\\//}"

    # Skip known entry-point files
    skip=false
    for skip_file in "${SKIP_FILES[@]}"; do
        sfn="${skip_file//\\//}"
        [[ "$rel_path" == "$sfn" ]] && { skip=true; break; }
    done
    $skip && continue

    # Build the import pattern to search for:
    #   package:kongossa/<path_without_lib_prefix>
    import_path="package:kongossa/${rel_path#lib/}"

    # Search for imports of this file in ALL other .dart files
    # grep uses lines starting with 'import' (single or double quotes)
    if ! grep -r \
        -e "^import[[:space:]]*['\"]$import_path['\"]" \
        --include='*.dart' \
        --exclude="$rel_path" \
        "$LIB_DIR" \
        > /dev/null 2>&1; then

        # Also check relative imports by looking for the filename
        filename="$(basename "$file")"
        if ! grep -r \
            -e "^import[[:space:]]*['\"].*/\?$filename['\"]" \
            --include='*.dart' \
            --exclude="$rel_path" \
            "$LIB_DIR" \
            > /dev/null 2>&1; then

            # Finally check for `part of` directives
            stem="${filename%.dart}"
            if ! grep -r \
                -e "^part[[:space:]]+of[[:space:]]+.*$stem" \
                --include='*.dart' \
                --exclude="$rel_path" \
                "$LIB_DIR" \
                > /dev/null 2>&1; then

                echo "   ⚠️  $rel_path"
                orphaned_count=$((orphaned_count + 1))
            fi
        fi
    fi

done < <(find "$LIB_DIR" -name '*.dart' -type f | sort)

echo ""
echo "📊 Scanné: $total_count fichiers"
if [[ $orphaned_count -eq 0 ]]; then
    echo "✅ Aucun fichier orphelin détecté !"
    exit 0
else
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  ⚠️  $orphaned_count fichier(s) orphelin(s) trouvé(s)"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Ces fichiers ne sont importés nulle part."
    echo "Si c'est intentionnel (fichier d'entrée, généré),"
    echo "ajoutez-les à la liste SKIP_FILES dans le script."
    exit 1
fi
